In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
###sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are goood',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are goood']

In [4]:
###Define the vocabulary size
voc_size = 10000

In [5]:
##One Hot Representaion
one_hot_repr= [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6779, 3210, 6611, 2448],
 [6779, 3210, 6611, 9292],
 [6779, 6263, 6611, 7175],
 [9769, 2439, 904, 5598, 7853],
 [9769, 2439, 904, 5598, 645],
 [8274, 6779, 7958, 6611, 5072],
 [9437, 3103, 2805, 878]]

In [6]:
##word  embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6779 3210 6611 2448]
 [   0    0    0    0 6779 3210 6611 9292]
 [   0    0    0    0 6779 6263 6611 7175]
 [   0    0    0 9769 2439  904 5598 7853]
 [   0    0    0 9769 2439  904 5598  645]
 [   0    0    0 8274 6779 7958 6611 5072]
 [   0    0    0    0 9437 3103 2805  878]]


In [9]:
##feature representation
dim = 10


In [16]:
model = Sequential()
#model.add(Embedding(voc_size,dim,input_length = sent_length))
model = Sequential([
    Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,))
])

model.compile('adam','mse')

d:\Machine learning\SimpleRNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[[ 3.35440077e-02,  2.90351547e-02,  2.62547024e-02,
         -4.48594466e-02,  1.75714158e-02, -4.43717614e-02,
          3.40000056e-02, -1.32718682e-02, -2.41265446e-03,
         -3.56670134e-02],
        [ 3.35440077e-02,  2.90351547e-02,  2.62547024e-02,
         -4.48594466e-02,  1.75714158e-02, -4.43717614e-02,
          3.40000056e-02, -1.32718682e-02, -2.41265446e-03,
         -3.56670134e-02],
        [ 3.35440077e-02,  2.90351547e-02,  2.62547024e-02,
         -4.48594466e-02,  1.75714158e-02, -4.43717614e-02,
          3.40000056e-02, -1.32718682e-02, -2.41265446e-03,
         -3.56670134e-02],
        [ 3.35440077e-02,  2.90351547e-02,  2.62547024e-02,
         -4.48594466e-02,  1.75714158e-02, -4.43717614e-02,
          3.40000056e-02, -1.32718682e-02, -2.41265446e-03,
         -3.56670134e-02],
        [ 1.78217925e-02,  6.20362908e-03,  2.63905786e-02,
         -2.53488310e-02, -1.25633702e-02, -1.45235062e-02,
          4.71654870e-02,  2.42226832e-02, -4.554707